# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\論文程式\2019.12.16-version.Fast\test.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CamShow(object):
    def setupUi(self, CamShow):
        CamShow.setObjectName("CamShow")
        CamShow.setEnabled(True)
        CamShow.resize(1298, 831)
        CamShow.setMinimumSize(QtCore.QSize(1026, 0))
        CamShow.setMaximumSize(QtCore.QSize(1500, 850))
        self.centralwidget = QtWidgets.QWidget(CamShow)
        self.centralwidget.setObjectName("centralwidget")
        self.ROIFm = QtWidgets.QFrame(self.centralwidget)
        self.ROIFm.setGeometry(QtCore.QRect(0, 570, 501, 251))
        self.ROIFm.setFrameShape(QtWidgets.QFrame.Box)
        self.ROIFm.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ROIFm.setObjectName("ROIFm")
        self.DispCopyImg = QtWidgets.QLabel(self.ROIFm)
        self.DispCopyImg.setGeometry(QtCore.QRect(0, 10, 491, 216))
        self.DispCopyImg.setText("")
        self.DispCopyImg.setObjectName("DispCopyImg")
        self.label_7 = QtWidgets.QLabel(self.ROIFm)
        self.label_7.setGeometry(QtCore.QRect(430, 230, 71, 21))
        self.label_7.setStyleSheet("font: 12pt \"Calibri\";")
        self.label_7.setObjectName("label_7")
        self.FullFm = QtWidgets.QFrame(self.centralwidget)
        self.FullFm.setGeometry(QtCore.QRect(0, 0, 501, 521))
        self.FullFm.setStyleSheet("font: 12pt \"Calibri\";")
        self.FullFm.setFrameShape(QtWidgets.QFrame.Box)
        self.FullFm.setFrameShadow(QtWidgets.QFrame.Raised)
        self.FullFm.setObjectName("FullFm")
        self.ShowBt = QtWidgets.QPushButton(self.FullFm)
        self.ShowBt.setGeometry(QtCore.QRect(160, 420, 51, 28))
        self.ShowBt.setObjectName("ShowBt")
        self.StopBt = QtWidgets.QPushButton(self.FullFm)
        self.StopBt.setGeometry(QtCore.QRect(220, 420, 81, 28))
        self.StopBt.setObjectName("StopBt")
        self.RecordBt = QtWidgets.QPushButton(self.FullFm)
        self.RecordBt.setGeometry(QtCore.QRect(310, 420, 81, 28))
        self.RecordBt.setObjectName("RecordBt")
        self.DispLb = QtWidgets.QLabel(self.FullFm)
        self.DispLb.setGeometry(QtCore.QRect(0, 0, 491, 361))
        self.DispLb.setText("")
        self.DispLb.setObjectName("DispLb")
        self.FilePathLE = QtWidgets.QLineEdit(self.FullFm)
        self.FilePathLE.setGeometry(QtCore.QRect(70, 460, 311, 31))
        self.FilePathLE.setText("")
        self.FilePathLE.setReadOnly(True)
        self.FilePathLE.setObjectName("FilePathLE")
        self.label_4 = QtWidgets.QLabel(self.FullFm)
        self.label_4.setGeometry(QtCore.QRect(20, 460, 41, 31))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.FullFm)
        self.label_5.setGeometry(QtCore.QRect(420, 490, 71, 20))
        self.label_5.setObjectName("label_5")
        self.FilePathBt = QtWidgets.QToolButton(self.FullFm)
        self.FilePathBt.setGeometry(QtCore.QRect(390, 460, 31, 31))
        self.FilePathBt.setObjectName("FilePathBt")
        self.ExitBt = QtWidgets.QPushButton(self.FullFm)
        self.ExitBt.setGeometry(QtCore.QRect(400, 420, 61, 28))
        self.ExitBt.setObjectName("ExitBt")
        self.label_19 = QtWidgets.QLabel(self.FullFm)
        self.label_19.setGeometry(QtCore.QRect(20, 420, 51, 21))
        self.label_19.setStyleSheet("font: 10pt \"Arial\";")
        self.label_19.setObjectName("label_19")
        self.label_23 = QtWidgets.QLabel(self.FullFm)
        self.label_23.setGeometry(QtCore.QRect(280, 390, 31, 21))
        self.label_23.setObjectName("label_23")
        self.roi_Height = QtWidgets.QLineEdit(self.FullFm)
        self.roi_Height.setGeometry(QtCore.QRect(310, 390, 61, 22))
        self.roi_Height.setObjectName("roi_Height")
        self.label_24 = QtWidgets.QLabel(self.FullFm)
        self.label_24.setGeometry(QtCore.QRect(0, 360, 101, 21))
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.FullFm)
        self.label_25.setGeometry(QtCore.QRect(60, 390, 51, 21))
        self.label_25.setObjectName("label_25")
        self.roi_X = QtWidgets.QLineEdit(self.FullFm)
        self.roi_X.setGeometry(QtCore.QRect(110, 390, 61, 22))
        self.roi_X.setObjectName("roi_X")
        self.roi_Y = QtWidgets.QLineEdit(self.FullFm)
        self.roi_Y.setGeometry(QtCore.QRect(220, 390, 61, 22))
        self.roi_Y.setObjectName("roi_Y")
        self.label_26 = QtWidgets.QLabel(self.FullFm)
        self.label_26.setGeometry(QtCore.QRect(170, 390, 51, 21))
        self.label_26.setObjectName("label_26")
        self.Exposure = QtWidgets.QComboBox(self.FullFm)
        self.Exposure.setGeometry(QtCore.QRect(70, 420, 71, 21))
        self.Exposure.setStyleSheet("font: 10pt \"Calibri\";")
        self.Exposure.setObjectName("Exposure")
        self.Exposure.addItem("")
        self.Exposure.addItem("")
        self.Exposure.addItem("")
        self.Exposure.addItem("")
        self.Exposure.addItem("")
        self.Exposure.addItem("")
        self.GrayCheck = QtWidgets.QCheckBox(self.FullFm)
        self.GrayCheck.setGeometry(QtCore.QRect(390, 380, 71, 31))
        self.GrayCheck.setStyleSheet("")
        self.GrayCheck.setObjectName("GrayCheck")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(940, 10, 231, 41))
        self.label_8.setStyleSheet("font: 12pt \"Calibri\";")
        self.label_8.setObjectName("label_8")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(1060, 410, 41, 21))
        self.label.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(1110, 410, 41, 21))
        self.label_2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(1160, 410, 41, 21))
        self.label_3.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_3.setTextFormat(QtCore.Qt.AutoText)
        self.label_3.setObjectName("label_3")
        self.Wave = QtWidgets.QFrame(self.centralwidget)
        self.Wave.setGeometry(QtCore.QRect(510, 0, 301, 451))
        self.Wave.setAutoFillBackground(False)
        self.Wave.setStyleSheet("\n"
"border-color: rgb(170, 85, 0);")
        self.Wave.setFrameShape(QtWidgets.QFrame.Box)
        self.Wave.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Wave.setObjectName("Wave")
        self.label_6 = QtWidgets.QLabel(self.Wave)
        self.label_6.setGeometry(QtCore.QRect(10, 70, 21, 21))
        self.label_6.setObjectName("label_6")
        self.label_9 = QtWidgets.QLabel(self.Wave)
        self.label_9.setGeometry(QtCore.QRect(10, 100, 21, 21))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.Wave)
        self.label_10.setGeometry(QtCore.QRect(10, 130, 21, 21))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.Wave)
        self.label_11.setGeometry(QtCore.QRect(10, 160, 21, 21))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.Wave)
        self.label_12.setGeometry(QtCore.QRect(10, 190, 21, 20))
        self.label_12.setObjectName("label_12")
        self.results_window = QtWidgets.QTextEdit(self.Wave)
        self.results_window.setGeometry(QtCore.QRect(10, 300, 281, 141))
        self.results_window.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.results_window.setObjectName("results_window")
        self.label_13 = QtWidgets.QLabel(self.Wave)
        self.label_13.setGeometry(QtCore.QRect(30, 40, 41, 21))
        self.label_13.setStyleSheet("font: 10pt \"Calibri\";\n"
"")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.Wave)
        self.label_14.setGeometry(QtCore.QRect(90, 40, 61, 20))
        self.label_14.setStyleSheet("font: 10pt \"Calibri\";")
        self.label_14.setObjectName("label_14")
        self.BtnGo = QtWidgets.QPushButton(self.Wave)
        self.BtnGo.setGeometry(QtCore.QRect(160, 230, 91, 31))
        self.BtnGo.setStyleSheet("background:rgb(255, 255, 127)")
        self.BtnGo.setObjectName("BtnGo")
        self.label_15 = QtWidgets.QLabel(self.Wave)
        self.label_15.setGeometry(QtCore.QRect(110, 270, 101, 31))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.Wave)
        self.label_16.setGeometry(QtCore.QRect(10, 10, 91, 31))
        self.label_16.setStyleSheet("font: 75 12pt \"Calibri\";")
        self.label_16.setObjectName("label_16")
        self.P1 = QtWidgets.QLineEdit(self.Wave)
        self.P1.setGeometry(QtCore.QRect(30, 70, 51, 22))
        self.P1.setObjectName("P1")
        self.W1 = QtWidgets.QLineEdit(self.Wave)
        self.W1.setGeometry(QtCore.QRect(90, 70, 51, 22))
        self.W1.setText("")
        self.W1.setReadOnly(False)
        self.W1.setObjectName("W1")
        self.W2 = QtWidgets.QLineEdit(self.Wave)
        self.W2.setGeometry(QtCore.QRect(90, 100, 51, 22))
        self.W2.setText("")
        self.W2.setReadOnly(False)
        self.W2.setObjectName("W2")
        self.P2 = QtWidgets.QLineEdit(self.Wave)
        self.P2.setGeometry(QtCore.QRect(30, 100, 51, 22))
        self.P2.setObjectName("P2")
        self.P3 = QtWidgets.QLineEdit(self.Wave)
        self.P3.setGeometry(QtCore.QRect(30, 130, 51, 22))
        self.P3.setObjectName("P3")
        self.W3 = QtWidgets.QLineEdit(self.Wave)
        self.W3.setGeometry(QtCore.QRect(90, 130, 51, 22))
        self.W3.setText("")
        self.W3.setReadOnly(False)
        self.W3.setObjectName("W3")
        self.P4 = QtWidgets.QLineEdit(self.Wave)
        self.P4.setGeometry(QtCore.QRect(30, 160, 51, 22))
        self.P4.setObjectName("P4")
        self.W4 = QtWidgets.QLineEdit(self.Wave)
        self.W4.setGeometry(QtCore.QRect(90, 160, 51, 22))
        self.W4.setText("")
        self.W4.setReadOnly(False)
        self.W4.setObjectName("W4")
        self.P5 = QtWidgets.QLineEdit(self.Wave)
        self.P5.setGeometry(QtCore.QRect(30, 190, 51, 22))
        self.P5.setObjectName("P5")
        self.W5 = QtWidgets.QLineEdit(self.Wave)
        self.W5.setGeometry(QtCore.QRect(90, 190, 51, 22))
        self.W5.setText("")
        self.W5.setReadOnly(False)
        self.W5.setObjectName("W5")
        self.label_18 = QtWidgets.QLabel(self.Wave)
        self.label_18.setGeometry(QtCore.QRect(50, 230, 41, 21))
        self.label_18.setObjectName("label_18")
        self.comboBox = QtWidgets.QComboBox(self.Wave)
        self.comboBox.setGeometry(QtCore.QRect(100, 230, 41, 31))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.P6 = QtWidgets.QLineEdit(self.Wave)
        self.P6.setGeometry(QtCore.QRect(170, 70, 51, 22))
        self.P6.setObjectName("P6")
        self.label_30 = QtWidgets.QLabel(self.Wave)
        self.label_30.setGeometry(QtCore.QRect(140, 70, 31, 21))
        self.label_30.setObjectName("label_30")
        self.W6 = QtWidgets.QLineEdit(self.Wave)
        self.W6.setGeometry(QtCore.QRect(230, 70, 51, 22))
        self.W6.setText("")
        self.W6.setReadOnly(False)
        self.W6.setObjectName("W6")
        self.label_31 = QtWidgets.QLabel(self.Wave)
        self.label_31.setGeometry(QtCore.QRect(230, 40, 61, 20))
        self.label_31.setStyleSheet("font: 10pt \"Calibri\";")
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(self.Wave)
        self.label_32.setGeometry(QtCore.QRect(170, 40, 41, 21))
        self.label_32.setStyleSheet("font: 10pt \"Calibri\";\n"
"")
        self.label_32.setObjectName("label_32")
        self.P7 = QtWidgets.QLineEdit(self.Wave)
        self.P7.setGeometry(QtCore.QRect(170, 100, 51, 22))
        self.P7.setObjectName("P7")
        self.W7 = QtWidgets.QLineEdit(self.Wave)
        self.W7.setGeometry(QtCore.QRect(230, 100, 51, 22))
        self.W7.setText("")
        self.W7.setReadOnly(False)
        self.W7.setObjectName("W7")
        self.label_46 = QtWidgets.QLabel(self.Wave)
        self.label_46.setGeometry(QtCore.QRect(140, 100, 31, 21))
        self.label_46.setObjectName("label_46")
        self.P8 = QtWidgets.QLineEdit(self.Wave)
        self.P8.setGeometry(QtCore.QRect(170, 130, 51, 22))
        self.P8.setObjectName("P8")
        self.label_47 = QtWidgets.QLabel(self.Wave)
        self.label_47.setGeometry(QtCore.QRect(140, 130, 31, 21))
        self.label_47.setObjectName("label_47")
        self.W8 = QtWidgets.QLineEdit(self.Wave)
        self.W8.setGeometry(QtCore.QRect(230, 130, 51, 22))
        self.W8.setObjectName("W8")
        self.P9 = QtWidgets.QLineEdit(self.Wave)
        self.P9.setGeometry(QtCore.QRect(170, 160, 51, 22))
        self.P9.setObjectName("P9")
        self.label_48 = QtWidgets.QLabel(self.Wave)
        self.label_48.setGeometry(QtCore.QRect(140, 160, 31, 21))
        self.label_48.setObjectName("label_48")
        self.W9 = QtWidgets.QLineEdit(self.Wave)
        self.W9.setGeometry(QtCore.QRect(230, 160, 51, 22))
        self.W9.setObjectName("W9")
        self.P10 = QtWidgets.QLineEdit(self.Wave)
        self.P10.setGeometry(QtCore.QRect(170, 190, 51, 22))
        self.P10.setObjectName("P10")
        self.label_49 = QtWidgets.QLabel(self.Wave)
        self.label_49.setGeometry(QtCore.QRect(140, 190, 31, 21))
        self.label_49.setObjectName("label_49")
        self.W10 = QtWidgets.QLineEdit(self.Wave)
        self.W10.setGeometry(QtCore.QRect(230, 190, 51, 22))
        self.W10.setObjectName("W10")
        self.graphicsView = PlotWidget(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(510, 520, 301, 301))
        self.graphicsView.setObjectName("graphicsView")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(550, 470, 211, 41))
        self.label_17.setStyleSheet("font: 12pt \"Calibri\";")
        self.label_17.setObjectName("label_17")
        self.draw_2 = PlotWidget(self.centralwidget)
        self.draw_2.setGeometry(QtCore.QRect(820, 60, 471, 391))
        self.draw_2.setObjectName("draw_2")
        self.draw_3 = PlotWidget(self.centralwidget)
        self.draw_3.setGeometry(QtCore.QRect(820, 520, 471, 301))
        self.draw_3.setObjectName("draw_3")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(830, 460, 231, 51))
        self.label_21.setStyleSheet("font: 12pt \"Calibri\";")
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(1210, 410, 61, 21))
        self.label_22.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_22.setTextFormat(QtCore.Qt.AutoText)
        self.label_22.setObjectName("label_22")
        self.FpsLCD = QtWidgets.QLCDNumber(self.centralwidget)
        self.FpsLCD.setGeometry(QtCore.QRect(140, 530, 71, 31))
        self.FpsLCD.setObjectName("FpsLCD")
        self.WidthLCD = QtWidgets.QLCDNumber(self.centralwidget)
        self.WidthLCD.setGeometry(QtCore.QRect(300, 530, 71, 31))
        self.WidthLCD.setObjectName("WidthLCD")
        self.HeightLCD = QtWidgets.QLCDNumber(self.centralwidget)
        self.HeightLCD.setGeometry(QtCore.QRect(390, 530, 71, 31))
        self.HeightLCD.setObjectName("HeightLCD")
        self.label_27 = QtWidgets.QLabel(self.centralwidget)
        self.label_27.setGeometry(QtCore.QRect(40, 530, 101, 31))
        self.label_27.setStyleSheet("font: 1ㄅpt \"Calibri\";")
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.centralwidget)
        self.label_28.setGeometry(QtCore.QRect(230, 530, 71, 31))
        self.label_28.setStyleSheet("font: 12pt \"Calibri\";")
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.centralwidget)
        self.label_29.setGeometry(QtCore.QRect(370, 530, 21, 31))
        self.label_29.setStyleSheet("font: 12pt \"Calibri\";")
        self.label_29.setObjectName("label_29")
        self.Btn_Log = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_Log.setGeometry(QtCore.QRect(1180, 480, 101, 31))
        self.Btn_Log.setObjectName("Btn_Log")
        self.Avg_logout = QtWidgets.QLineEdit(self.centralwidget)
        self.Avg_logout.setGeometry(QtCore.QRect(1130, 480, 41, 31))
        self.Avg_logout.setObjectName("Avg_logout")
        self.label_33 = QtWidgets.QLabel(self.centralwidget)
        self.label_33.setGeometry(QtCore.QRect(1090, 460, 41, 51))
        self.label_33.setObjectName("label_33")
        self.draw_2.raise_()
        self.ROIFm.raise_()
        self.FullFm.raise_()
        self.label_8.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.Wave.raise_()
        self.graphicsView.raise_()
        self.label_17.raise_()
        self.draw_3.raise_()
        self.label_21.raise_()
        self.label_22.raise_()
        self.FpsLCD.raise_()
        self.WidthLCD.raise_()
        self.HeightLCD.raise_()
        self.label_27.raise_()
        self.label_28.raise_()
        self.label_29.raise_()
        self.Btn_Log.raise_()
        self.Avg_logout.raise_()
        self.label_33.raise_()
        CamShow.setCentralWidget(self.centralwidget)

        self.retranslateUi(CamShow)
        QtCore.QMetaObject.connectSlotsByName(CamShow)

    def retranslateUi(self, CamShow):
        _translate = QtCore.QCoreApplication.translate
        CamShow.setWindowTitle(_translate("CamShow", "CamShow"))
        self.label_7.setText(_translate("CamShow", "<html><head/><body><p><span style=\" font-size:10pt; color:#8d4600;\">ROI 影像</span></p></body></html>"))
        self.ShowBt.setText(_translate("CamShow", "Start"))
        self.StopBt.setText(_translate("CamShow", "Stop"))
        self.RecordBt.setText(_translate("CamShow", "Save"))
        self.label_4.setText(_translate("CamShow", "<html><head/><body><p><span style=\" font-weight:600;\">路徑:</span></p></body></html>"))
        self.label_5.setText(_translate("CamShow", "<html><head/><body><p align=\"center\"><span style=\" font-size:9pt; color:#8d4600;\">及時全影像</span></p></body></html>"))
        self.FilePathBt.setToolTip(_translate("CamShow", "<html><head/><body><p align=\"center\">...</p><p align=\"center\"><br/></p></body></html>"))
        self.FilePathBt.setText(_translate("CamShow", "..."))
        self.ExitBt.setText(_translate("CamShow", "Exit"))
        self.label_19.setText(_translate("CamShow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">曝光:</span></p></body></html>"))
        self.label_23.setText(_translate("CamShow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt;\">H:</span></p></body></html>"))
        self.label_24.setText(_translate("CamShow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600; color:#8d4600;\">ROI Setting</span></p></body></html>"))
        self.label_25.setText(_translate("CamShow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt;\">起始X:</span></p></body></html>"))
        self.label_26.setText(_translate("CamShow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt;\">起始Y :</span></p></body></html>"))
        self.Exposure.setItemText(0, _translate("CamShow", "0.033"))
        self.Exposure.setItemText(1, _translate("CamShow", "0.016"))
        self.Exposure.setItemText(2, _translate("CamShow", "0.008"))
        self.Exposure.setItemText(3, _translate("CamShow", "0.004"))
        self.Exposure.setItemText(4, _translate("CamShow", "0.002"))
        self.Exposure.setItemText(5, _translate("CamShow", "0.001"))
        self.GrayCheck.setToolTip(_translate("CamShow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">Gary</span></p></body></html>"))
        self.GrayCheck.setWhatsThis(_translate("CamShow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">Gary</span></p></body></html>"))
        self.GrayCheck.setText(_translate("CamShow", "Gary"))
        self.label_8.setText(_translate("CamShow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; color:#8d4600;\">Sensor View Point</span></p></body></html>"))
        self.label.setText(_translate("CamShow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; color:#ff0000;\">— R: </span></p><p><br/></p><p><span style=\" font-size:10pt;\"><br/></span></p></body></html>"))
        self.label_2.setText(_translate("CamShow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; color:#00ff00;\">— G:</span></p><p><span style=\" font-size:10pt;\"><br/></span></p></body></html>"))
        self.label_3.setText(_translate("CamShow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; color:#0000ff;\">— B:</span></p><p><span style=\" font-size:10pt;\"><br/></span></p></body></html>"))
        self.label_6.setText(_translate("CamShow", "<html><head/><body><p align=\"center\"><span style=\" font-size:9pt; font-weight:600;\">1:</span></p></body></html>"))
        self.label_9.setText(_translate("CamShow", "<html><head/><body><p align=\"center\"><span style=\" font-size:9pt; font-weight:600;\">2:</span></p></body></html>"))
        self.label_10.setText(_translate("CamShow", "<html><head/><body><p align=\"center\"><span style=\" font-size:9pt; font-weight:600;\">3:</span></p></body></html>"))
        self.label_11.setText(_translate("CamShow", "<html><head/><body><p align=\"center\"><span style=\" font-size:9pt; font-weight:600;\">4:</span></p></body></html>"))
        self.label_12.setText(_translate("CamShow", "<html><head/><body><p align=\"center\"><span style=\" font-size:9pt; font-weight:600;\">5:</span></p></body></html>"))
        self.label_13.setText(_translate("CamShow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; color:#0000ff;\">Pixel </span></p></body></html>"))
        self.label_14.setText(_translate("CamShow", "<html><head/><body><p align=\"center\"><span style=\" font-family:\'arial,sans-serif\'; font-size:12pt; font-weight:600; color:#0000ff; background-color:#ffffff;\">λ </span><span style=\" font-size:12pt; font-weight:600; color:#0000ff;\">(nm)</span></p></body></html>"))
        self.BtnGo.setText(_translate("CamShow", "計算校正"))
        self.label_15.setText(_translate("CamShow", "<html><head/><body><p align=\"center\"><span style=\" font-size:9pt; font-weight:600; color:#b37759;\">校正結果</span></p></body></html>"))
        self.label_16.setText(_translate("CamShow", "<html><head/><body><p><span style=\" font-weight:600; color:#550000;\">波長校正</span></p></body></html>"))
        self.label_18.setText(_translate("CamShow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; color:#0000ff;\">冪次:</span></p></body></html>"))
        self.comboBox.setItemText(0, _translate("CamShow", "1"))
        self.comboBox.setItemText(1, _translate("CamShow", "2"))
        self.comboBox.setItemText(2, _translate("CamShow", "3"))
        self.comboBox.setItemText(3, _translate("CamShow", "4"))
        self.comboBox.setItemText(4, _translate("CamShow", "5"))
        self.label_30.setText(_translate("CamShow", "<html><head/><body><p align=\"center\"><span style=\" font-size:9pt; font-weight:600;\">6:</span></p></body></html>"))
        self.label_31.setText(_translate("CamShow", "<html><head/><body><p align=\"center\"><span style=\" font-family:\'arial,sans-serif\'; font-size:12pt; font-weight:600; color:#0000ff; background-color:#ffffff;\">λ </span><span style=\" font-size:12pt; font-weight:600; color:#0000ff;\">(nm)</span></p></body></html>"))
        self.label_32.setText(_translate("CamShow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; color:#0000ff;\">Pixel </span></p></body></html>"))
        self.label_46.setText(_translate("CamShow", "<html><head/><body><p align=\"center\"><span style=\" font-size:9pt; font-weight:600;\">7:</span></p></body></html>"))
        self.label_47.setText(_translate("CamShow", "<html><head/><body><p align=\"center\"><span style=\" font-size:9pt; font-weight:600;\">8:</span></p></body></html>"))
        self.label_48.setText(_translate("CamShow", "<html><head/><body><p align=\"center\"><span style=\" font-size:9pt; font-weight:600;\">9:</span></p></body></html>"))
        self.label_49.setText(_translate("CamShow", "<html><head/><body><p align=\"center\"><span style=\" font-size:9pt; font-weight:600;\">10:</span></p></body></html>"))
        self.label_17.setText(_translate("CamShow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; color:#8d4600;\">Curve Fitting Plot</span></p></body></html>"))
        self.label_21.setText(_translate("CamShow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; color:#8d4600;\">Calibrated View Point</span></p></body></html>"))
        self.label_22.setText(_translate("CamShow", "<html><head/><body><p><span style=\" font-weight:600; color:#ffffff;\">— Gary:</span></p><p><span style=\" color:#ffffff;\"><br/></span></p></body></html>"))
        self.label_27.setText(_translate("CamShow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600; color:#550000;\">Frame Rate:</span></p></body></html>"))
        self.label_28.setText(_translate("CamShow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600; color:#550000;\">Image:</span></p></body></html>"))
        self.label_29.setText(_translate("CamShow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600; color:#550000;\">X</span></p></body></html>"))
        self.Btn_Log.setToolTip(_translate("CamShow", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600; color:#0000ff;\">匯出光譜數值</span></p></body></html>"))
        self.Btn_Log.setText(_translate("CamShow", "匯出光譜數值"))
        self.label_33.setText(_translate("CamShow", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600; color:#0000ff;\">平均</span></p><p><span style=\" font-size:9pt; font-weight:600; color:#0000ff;\">次數:</span></p></body></html>"))
from pyqtgraph import PlotWidget
